[package]
name = "abeehive"
version = "0.0.3"
edition = "2021"

[dependencies]
anyhow = "1.0.100"

wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4"
gloo = "0.11.0"
yew = { version = "0.21", features = ["csr"] }
yewdux = "0.11.0"
web-sys = { version = "0.3.56", features = ["HtmlInputElement", "HtmlSelectElement"] }
js-sys = "0.3"
serde = { version = "1.0.226", features = ["derive"] }
serde-wasm-bindgen = "0.6"
regex = "1.10.4"
toml = "0.9.7"

base64 = "0.22.1"

[lib]
name = "abeehive"
path = "src/lib.rs"
